
version: 3

sources: 
  - name: raw_data 
    database: Betting
    schema: staging
    tables: 
      - name: bets


models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  
  - name: bets_transformed
    description: 'Transformed bets table with timezone conversion and additional fields'
    columns: 
      - name: bet_id
        description: 'Unique identifier for each bet'
        data_tests:
          - unique
          - not_null

      - name: user_id
        description: 'Unique identifier for each user'
        data_tests:
          - not_null

